### ISSUE TITLE
为啥我加了主主题文件 四叶草也配置了主题名称却还是不起作用

### ISSUE THREAD

**Issue by wjswjw** [yangbe/z370n-wifi-vega64#14]
为啥我加了主主题文件 四叶草也配置了主题名称却还是不起作用，自带的主题太简约了 感觉和OC的默认主题一样  大神看到了麻烦指点一二

**Comment by yangbe** [comment]
![image](https://user-images.githubusercontent.com/9880101/82719056-b531d680-9cd9-11ea-95bd-a298576cca17.png)
